
(defun sweyla840358 ()
  "Theme generated by Sweyla: http://sweyla.com/themes/seed/840358/"
  (interactive)
  (color-theme-install
   '(sweyla840358
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#70FFB1"))))
     (font-lock-constant-face ((t (:foreground "#636ABB"))))
     (font-lock-builtin-face ((t (:foreground "#006DFF"))))
     (font-lock-function-name-face ((t (:foreground "#82643F"))))
     (font-lock-variable-name-face ((t (:foreground "#819760"))))
     (font-lock-keyword-face ((t (:foreground "#38C7FB"))))
     (font-lock-string-face ((t (:foreground "#32FA00"))))
     (font-lock-doc-string-face ((t (:foreground "#32FA00"))))
     (font-lock-type-face ((t (:foreground "#8087C9"))))
     )))

(provide 'sweyla840358)
